### ISSUE TITLE
Support for multi-year grants

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#704]
### Summary

Some giving projects are now giving out two-year grants. How they work:
- 1 application - giving project combo (like current awards)
- 1 decision process by the GP
- 1 agreement
- 2 checks
- 2 year-end reports
- Reports should show total amount, not split by year
- May expand to beyond 2 years in the future (but not any time soon)

-----

#### Notes: Technical considerations

- One grant object
 - _May require additional work to expand to 3+_
 - Less query overhead
 - Matches the concept more - "one two-year grant" not "two grants"
- One grant object per year
  - By setting up for 2, we are also set up for 3+ automatically
  - _If first one has different requirements than following ones (agreement, maybe) that could be complicated_
- Both
  - Easily backwards compatible (existing grants not affected)
  - _May be complex to set up a good admin interface_

I'm leaning heavily toward expanding the current `GivingProjectGrant` to allow it to be multi-year. 3-year would be easy to incorporate if they do that later. 

----

- org_home does query for yer for each award - update

**Comment by aisapatino** [comment]
- Two year-end reports
- Track separate disbursement
- Show total sum for reports (don't split per year)

Could expand to multiyear past 2

I think single multiyear grant object would make sense except need to think about making it expandable

**Comment by tarhata** [comment]
More clarification from Sunny:
>Here's some context about how we handle our grants. In sum, we just need the ability to add multiple grant awards to one application. I think that will take care of our needs.

>1. Our GP make grant recommendations. 
>2. Our board approves.
>3. Sunny updates Project Central by adding grant awards for year one.
>4. I send out grant paperwork that says they will get year one at the next disbursement date and year two upon completion of grant requirements (YER and submitting pictures).
>5. I collect all agreements and then pass them to Lynne, Operations Manager.
>6. Lynne creates grant checks to mail to grantees.
>7. Sunny enters grant award amounts and check number in Project Central and then mails out the checks.
>8. Grantees complete their year end report...
>9? do we need them to sign another agreement for the second year?

**Comment by tarhata** [comment]
See my notes about this issue on google docs [here](https://docs.google.com/document/d/1B3a8zbZGFRbqM02tvxWZMMNbH6QSyLvp9LMRFhhQwsc/edit?usp=sharing)

**Comment by tarhata** [comment]
###### STEP ONE:  Update GivingProjectGrant model
- [ ] Add new fields: `second_amount`, `second_check_number`, `second_check_mailed`
- [ ] Add new methods to GPG model:
     - `total_amount()`- returns amount + second_amount, or just amount if second_amount is blank
     - `grant_length()` - returns 1 for single-year grant (if second_amount is blank) or 2 for two-year grant. Returning integer because of ability to use it in a description, ex. "1 year grant" or "2 year grant"

- [ ] Update `yearend_due()` - returns the next due date of a year-end report (if second_check_mailed is filled in, and the first due date has passed, it would return the due date for the second one)

- [ ] Add a couple unit tests for the new GPG methods to make sure they return the correct things. For this, instead of testing responses, you would just be creating new GPG instances, then calling the new methods and asserting that they return whatever you expect. (I can help with this by creating a couple ones as examples)

- [ ] Update `amount` to refer to `total_amount()`  in org home page and giving project grant admin sites

**Comment by tarhata** [comment]
###### STEP TWO:  Update YERDraft and YER models and relationship to GPG
- [ ] Change YERDraft/GPG and YER/GPG relationships to [ForeignKey](https://docs.djangoproject.com/en/1.5/ref/models/fields/#foreignkey)
- [ ] Update YERDraft and YER references to use many-to-one queries
     - Check organization home page, admin, email reminders, grant display

**Comment by tarhata** [comment]
###### STEP THREE:  Check and update YER Tests, including adding tests for second year end reports
- [x] Update YER tests so that they don't fail
- [x] Add test to verify second year end report reminder email sent
- [x] Add test to verify that no email sent if both year end reports are completed for a two-year grant

**Comment by tarhata** [comment]
I think I got this done! :grinning: Let me know if there's anything that needs to be updated or fixed.

**Comment by aisapatino** [comment]
Cool! I will take a look at this on Thursday probably, and if there are any changes needed I can make them myself no problem.
