### ISSUE TITLE
Reporting - order grant cycles

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#741]
not urgent but when we go to run a grants report the grant cycles in the filter criteria section are in no discernible order. It'd be nice if they could be sorted by deadline date or something else logical.

![image](https://cloud.githubusercontent.com/assets/1279315/6754573/afa7fe7e-ceda-11e4-8a8c-9a1119de75f8.png)

[asana](https://app.asana.com/0/5175284945766/29705568491288)

**Comment by aisapatino** [comment]
Example of model ordering: https://github.com/aisapatino/sjfnw/commit/a73e55c5fbf56fe91302f366b6fb6a42b88385ac

**Comment by tarhata** [comment]
Hey, so I finally figured this out! Turns out that running `set(choices)` was mucking with the alphabetical ordering of `title`. According to this forum [post](http://stackoverflow.com/questions/15181867/understanding-the-set-function) and [this explanation of set()] (http://www.python-course.eu/sets_frozensets.php), `set` returns a set of unordered values, even if the original list was ordered. So all I did was add `sorted(set(choices))` to keep the field choices alphabetized by `title`

**Comment by tarhata** [comment]
Also, I realized I forgot to pull `master` first. Since this is a simple fix, would you just directly change `master` instead and delete this branch? Or should I rebase master for this branch and then push it?

**Comment by aisapatino** [comment]
Nice work figuring that out. I had thought it would be as simple as adding the `ordering` field.

I used `set` to remove duplicates - giving projects and grant cycles can (and often will) have the same title. They're usually displayed with the year attached to distinguish them. This filter would allow them to filter by, for example, all General Grant Cycles, or, if they select year limits, to filter to a specific one. A bit more flexible (and much more readable) than listing out every single GP and grant cycle.

More to the point, though, I used `set` because I must not have known about [`distinct()`](https://docs.djangoproject.com/en/1.5/ref/models/querysets/#django.db.models.query.QuerySet.distinct) at the time. It should work just as well and be a bit simpler. It can be chained onto the existing `values_list` query. Here's an [example](https://github.com/aisapatino/sjfnw/blob/e2099c30524b20d1ace978edbd6b703d6a71a330/sjfnw/grants/admin.py#L29)

Re: branching
Usually, if there are no conflicts, it's fine and you can merge anyway. When you open a PR, it will tell you whether it's clear to merge or not (separate from the test results, github checks whether there will be merge conflicts)

I'd probably try that first and see if it works, then we can explore more complicated options (duplicating the commit, dealing with the merge conflicts) if you need to.

**Comment by tarhata** [comment]
I see. I read about distinct() but wasn't sure whether or not to use it
since I felt unclear about how the app was querying the Giving  Project
choices and why you had used set() instead.

Question: Is calling functions directly on database queries faster or equal
to running built-in functions python?

For example, the code you linked to
<https://github.com/aisapatino/sjfnw/blob/e2099c30524b20d1ace978edbd6b703d6a71a330/sjfnw/grants/admin.py#L29>
is
first looking up the values, then removing duplicates using distinct(),
then ordering them by title. In my head, I would think that python's built
in sort() and set() functions might be faster. But then again, the
initial iterable
passed to set() would be bigger if there are duplicates. Guess it depends
how queries are done in GAE.

**Comment by aisapatino** [comment]
Good question. I don't recall any reason for `set`. I'm guessing I just didn't know you could do it at the database level.

Those chained functions are not actually a series of separate steps, even though it looks like that - a lot of it is done at the same time. That query:

```python
titles = models.GrantCycle.objects.values_list('title', flat=True)
    .distinct().order_by('title')
```
creates a SQL query something like

```sql
SELECT DISTINCT title FROM fund_grantcycle ORDER BY title;
```

So duplicates, selecting certain columns, and ordering are all done at the database level, before the results are received by django. Then I'm assuming django handles the `values_list` formatting.

I'm not sure about using database builtins vs manipulating the data in python. I've been told that it's generally faster to use built-in database functions when they exist. The idea being that databases are optimized for those specific things. I can't find anything definitive on the subject though. Here's one discussion about that as it related to sorting 

http://stackoverflow.com/questions/5097942/how-expensive-is-sql-order-by

**Comment by tarhata** [comment]
It actually makes sense that database queries would be faster since that's
what they're optimized for. So I'll go with that. However, I'm wondering if
it makes a difference that this is all happening in the cloud, especially
since you mentioned that the current slowness of the app is due to all the
different queries being made.

**Comment by aisapatino** [comment]
The slowness is usually due to the _number_ of queries being made - I was probably talking about the admin site, which is very slow in certain parts because the Django admin code is doing a bunch of repetitive queries. The complexity of the query adds time at the database level, but doesn't affect the time it takes to contact the db, which is the bulk of it, I believe. So the main thing is to use fewer queries when possible - for example, doing `.select_related()` at the start if you know you'll need the related objects, rather than doing additional queries.

Next time we meet I can show you a django profiling tool that shows the time taken for different database queries.

**Comment by aisapatino** [comment]
This is done, right? I think you checked it off in Asana. Go ahead and close it here if so
