### ISSUE TITLE
Admin - Show screening status/awards on organization page

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#742]
### Background

The current grant application inline on the org page looks like this

![org-app-inline](https://cloud.githubusercontent.com/assets/1279315/7107628/c3333e34-e11f-11e4-9022-dbe76525cbde.png)

It is defined by [`GrantApplicationI`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/admin.py#L134) in `sjfnw/grants/admin.py`

### Requested change

[Asana task](https://app.asana.com/0/5175284945766/29705568491300). They would like to show screening status (`ProjectApp.screening_status`) and awards (`GivingProjectGrant.amount`s) as well.  The trick is, one grant application can be assigned to multiple giving projects and could therefore have more than one status/award. So we will need to compile any related awards and display them in a single field.

**Desired outcome**: A new column in the inline that shows a summary of giving projects assigned to that app. Something like
```
Next Generation Giving Project: Grant Issued, $5,000
```
```
Next Generation Giving Project: Grant Issued, $10,000
LGBTQ Giving Project: Site Visit Granted`
```

### How to
Inlines allow custom methods that can be displayed along with actual model fields (as long as they're read-only - see [docs for `ModelAdmin.readonly_fields`](https://docs.djangoproject.com/en/1.5/ref/contrib/admin/#django.contrib.admin.ModelAdmin.readonly_fields)). `GrantApplicationI.edit_application` is an example of this.

What we want is a new method on `GrantApplicationI` that returns text displaying screening statuses and awards as shown above.

#### Suggested steps
Just one idea of how to approach it, edit as you wish!

1. Get a new column to display in the inline with any arbitrary text. That means
  - [x] Add a method to `GrantApplicationI` that returns a string
  - [x] Register the new method as a read-only field on the inline. See readonly docs linked above and the existing `edit_application` method as examples.
  - [x] Load the page via local server and verify that the new column shows
2. Figure out how to get related `ProjectApp`s from inside the admin method, use them to display screening status.
  - [x] Display screening statuses
  - [x] Display giving project with each screening status
  - Background:
    -  Your new method will get two arguments: `self`, an instance of `GrantApplicationI`, and `obj`, the `GrantApplication` object that the inline is tied to.
    - See [the model diagram](https://docs.google.com/drawings/d/1BZFuO1DqlMbgg7ItrIS0L3x5oHzsoxoL5e5fGGM-5HQ/edit) for how `GivingProjectGrant`s are connection to an `Organization`.
    - You've probably seen queries all over the code, I'm not sure how much you've interacted with them yet. There's an intro [here](https://docs.djangoproject.com/en/1.5/topics/db/queries/).
    - You can verify if you've gotten something/the right something by printing it out (either returning it so it gets displayed in the inline, or logging it out to the console).
3. Add awards to output string when applicable
  - [x] For each `ProjectApp`, check if there is a `GivingProjectGrant` pointing to it. If so, add the grant amount
4. Performance
  - Once the display looks good, we can talk about making some tweaks to help with performance. Admin pages tend to be very slow, especially pages that do a lot of lookups on related objects.

**Comment by aisapatino** [comment]
@tarhata As you've seen, I looked into this and it seems doable so I added a bunch of details on it. It's not as complicated as I may have made it appear with that wall of text, I just wanted to be thorough. Definitely let me know if you get stuck on anything, or if you want me to look at what you're doing.

**Comment by tarhata** [comment]
Mehhh, I really struggled with this one! Not sure if this is the best way to go about this, but hopefully you get an idea of what my line of thinking was. Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/8212941/7218914/8c802598-e63b-11e4-87a9-812477a2f2bb.png)

As you can see above, I got it to display the correct screening statuses for those which have a grant issued, but there's a `None` value showing up when it should indicate the `pre_screening_status`. Also, I noticed that the `GrantApplication` inline would disappear for some organizations. For example:

![image](https://cloud.githubusercontent.com/assets/8212941/7218902/ffcd3de8-e63a-11e4-88e4-d1ec7e34fb1f.png)

Also, I added the `pre_status == 50` line as a way to check if all the other statuses would show (`pre_screening_status` < 50). They all do. But if `pre_screening_status` = 50 , sometimes the inline disappears. For example, I changed the above org's `pre_screening_status` to 40 and the inline shows again.

![image](https://cloud.githubusercontent.com/assets/8212941/7218909/420bc6d4-e63b-11e4-9b85-17c9035b4e4f.png)

I've been trying to debug this for the last few hours, and have come to the conclusion that the admin template or something related to the rendering of the inline crashes when [`projectapp = models.ProjectApp.objects.get(application_id=obj.pk)`](https://github.com/aisapatino/sjfnw/blob/25358185a0630b6c01b1f7ff768e13cf146bd0d3/sjfnw/grants/admin.py#L152) gets called. 

POSSIBLE CAUSES:
* Some `GrantApplication` objects don't have a `ProjectApp` tied to them because the database is weird??
* The way I'm accessing `ProjectApp`s `screening_status` is incorrect

QUESTIONS:
1. How come you can call [`pre_screening_status`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/admin.py#L137) as an inline even though the method to convert the `int` is in [views.py?] (https://github.com/aisapatino/sjfnw/blob/e2099c30524b20d1ace978edbd6b703d6a71a330/sjfnw/grants/views.py#L1072)

**Comment by aisapatino** [comment]
The problem seems to be that the admin site hides errors and either displays the inline with `(None)` or hides it entirely. I'm not sure which scenarios result in which display, but I did find the error, which is related to your questions

> Some GrantApplication objects don't have a ProjectApp tied to them because the database is weird??

`GrantApplication`s don't have to have a `ProjectApp`. `ProjectApp` represents a connection between an app and a giving project, so an app has one per giving project they are assigned to. So that could be zero, even with with a pre screening of 50 (maybe they've been pre-screened in, but no one has assigned them to a GP yet). I'll put a comment on the commit with more info about how to handle this.

> The way I'm accessing ProjectApps screening_status is incorrect
> 1. How come you can call pre_screening_status as an inline even though the method to convert the int is in views.py?

The way you're accessing it works - I checked by adding some `print` statements to your `summary` method and they showed that you were getting the human-readable version.

However, there is an easier way! (Which I didn't know about when I wrote that reporting code you linked). Sorry I forgot to mention this. Since model fields with `choices` are common, Django has a way to get the human-readable version instead of the raw db version. 

[`model.get_FOO_display()`](https://docs.djangoproject.com/en/1.5/ref/models/instances/#django.db.models.Model.get_FOO_display)

So you can do `obj.get_pre_screening_status_display()` or `obj.get_screening_status_display()` instead of having to do the convert dict lookup.

**Comment by tarhata** [comment]
Thanks for all your tips! I think I got it working correctly this time around. Definitely had wrong assumptions about how the grant application process worked, so next time I'm going to double check with you first because I spent way too much time debugging due to that! :expressionless:  

Not sure if is the most efficient way to do things, but you get the idea. Now I can sleep well. :relieved:

**Comment by aisapatino** [comment]
I was thinking, once you have any code committed, I think it might be easiest if you open a pull request and we continue discussing there instead of on the issue itself. That way code comments are in the same place as regular ones. Going to open a PR for this and then I'll take a look at the code.

**Comment by aisapatino** [comment]
Code is merged, closing
